!* ============================================================================ *
!*
!* Multi-Layer Shallow Water Model
!*
!* Version 1.4 - 20/05/2008 - ATvS
!*
!* ============================================================================ *
!
! This include file defines some constants that are used throughout the code.
! The intent is to make sure that the same values are used everywhere and to
! increase the readability of the code.
!
! Numbers for Fortran units.
      integer, parameter:: stderr = 0  ! stderr device.
      integer, parameter:: uout = 99   ! Unit for certain messages 
                                       ! generated by the code.
! 
! Mathematics constants.
      real, parameter:: pi   = 3.14159265358979323846264338328
      real, parameter:: tpi  = 2. * pi
      real, parameter:: pio2 = pi / 2.
