image: alpine/git:latest

pipelines:
  default:
    - step:
        name: Mirror to GitHub
        script:
          - git remote add github git@github.com:SouKot/do-method-cpp.git
          - git fetch --all --tags
          - git push github --all
          - git push github --tags
