//@HEADER
//-----------------------------------------------------------------------------
#ifndef Problem_Interface_H
#define Problem_Interface_H
//#include "BorderedSolver_EpetraHouseholder.H"
//#include "LinearSystem_AztecOO.H"
//#include "NOX_TestCompare.H"
#include "Teuchos_Array.hpp"
#include "Teuchos_LAPACK.hpp"
#include "Teuchos_Ptr.hpp"
#include "Teuchos_RCP.hpp"
#include "Teuchos_ScalarTraits.hpp"
#include "Teuchos_StandardCatchMacros.hpp"
#include "Teuchos_StrUtils.hpp"
#include "Teuchos_XMLParameterListHelpers.hpp"
#include "Teuchos_oblackholestream.hpp"
#include <Teuchos_SerialDenseMatrix.hpp>
#include <random>
// Trilinos Objects
#ifdef HAVE_MPI
#include "Epetra_MpiComm.h"
#else
#include "Epetra_SerialComm.h"
#endif
#include "Amesos.h"
#include "Amesos_BaseSolver.h"
#include "Amesos_ConfigDefs.h" //#include <random>
#include "BelosBlockGmresSolMgr.hpp"
#include "BelosConfigDefs.hpp"
#include "BelosEpetraAdapter.hpp"
#include "BelosIMGSOrthoManager.hpp"
#include "BelosLinearProblem.hpp"
#include "BelosMultiVec.hpp"
#include "Epetra_CrsMatrix.h"
#include "Epetra_LinearProblem.h"
#include "Epetra_Map.h"
#include "Epetra_MultiVector.h"
#include "Epetra_RowMatrix.h"
#include "Epetra_Vector.h"
#include "Ifpack.h"
#include <Epetra_SerialDenseMatrix.h>
// ---------- Standard Includes ----------
#include <iostream>
#include <string>
// class Epetra_LinearProblem;
// class Amesos_BaseSolver;
class AztecOO;
using namespace std;
extern "C" void dsytri_(char *UPLO, int *N, double *A, int *LDA, int *IPIV, double *Work, int *INFO);
class Problem_Interface
{
public:
  Problem_Interface(Teuchos::RCP<Epetra_CrsMatrix> A, // Teuchos::RCP<Epetra_CrsMatrix> A21,
                    Teuchos::RCP<Teuchos::ParameterList> SolverParams, Teuchos::RCP<Epetra_Vector> udet, int &m,
                    double *t, double &dt, Teuchos::RCP<Epetra_MultiVector> W, Teuchos::RCP<Epetra_CrsMatrix> mass,
                    int iter);
  ~Problem_Interface();
  //! Compute an explicit Jacobian
  bool computeJacobian(const Epetra_Vector &x, Epetra_Operator &Jac);
  void MOrth();
  int SolveV(Epetra_MultiVector& LHS, Epetra_MultiVector& RHS, std::string label);
  // Return a reference to the Epetra_Vector with the initial guess
  // that is generated by the FiniteElementProblem class.
  Epetra_Vector &getSolution()
  {
    return *(V->operator()(0));
  };
  // Return a reference to the Epetra_Vector with the Jacobian
  // that is generated by the FiniteElementProblem class.
  Epetra_CrsMatrix &getJacobian()
  {
    return *LHS_block_1_;
  };
  Teuchos::RCP<Epetra_MultiVector> getExp_yy()
  {
    return Exp_yy;
  };
  int v_stoch_init(Epetra_MultiVector *Vold);
  void computeBlocksold(double dt);
  void computeBlocks(double dt);
  void computeExpVal(double dt);
  Teuchos::RCP<Epetra_MultiVector> get_y()
  {
    return y;
  };
  void set_y(Epetra_MultiVector yy)
  {
    *y = yy;
  };
  double dt_;
  int m_;
  Teuchos::RCP<Teuchos::ParameterList> SolverParams_;
  /*!
   * \brief Call user routine for computing the shifted matrix
   * \f$\alpha J + \beta M\f$ where \f$J\f$ is the Jacobian matrix
   * and \f$M\f$ is the mass matrix.
   */
  bool computeShiftedMatrix(double alpha, double beta, const Epetra_Vector &x, Epetra_Operator &A);
  //! Set a parameter in the user's code.
  void init_v(double t);
  std::string InitFile_;
  Teuchos::RCP<Epetra_CrsMatrix> A_;
  Teuchos::RCP<Epetra_CrsMatrix> LHS_block_1_;
  Epetra_CrsMatrix *LHS_block_1;
  Teuchos::RCP<Epetra_CrsMatrix> mass_;
  Teuchos::RCP<Epetra_Vector> udet_;
  int stochiter, MyPID;
  double *t_, Tol_;
  double *r_val;
  Teuchos::RCP<Epetra_MultiVector> W_;
  Teuchos::RCP<Epetra_MultiVector> V, V1;
  Teuchos::RCP<Epetra_MultiVector> eye;
  Teuchos::RCP<Epetra_MultiVector> Exp_zy;
  Teuchos::RCP<Epetra_MultiVector> Exp_yy, Rvec;
  Teuchos::RCP<Epetra_MultiVector> Exp_yyy;
  Teuchos::RCP<Epetra_MultiVector> expv3;
  Teuchos::RCP<Teuchos::SerialDenseMatrix<int, double>> R;
  Teuchos::RCP<Epetra_MultiVector> exp_yy_inv, ExpDExpyy;
  Teuchos::RCP<Epetra_Map> map_, y_map;
  Teuchos::RCP<Epetra_MultiVector> z, y, RHS_block_1;
  Teuchos::RCP<Epetra_LocalMap> locmap_;
  Teuchos::RCP<Epetra_LinearProblem> v_prob;
  Teuchos::RCP<Amesos_BaseSolver> v_solve;
  // Teuchos::RCP<AztecOO> v_solve_iter;
  string solver_type;
  int iteration, MaxIter_, DbgLvl_;
  void PostProcess();
  void TransferNorm();
  bool test_, debug_;
  void printnormMV(Epetra_MultiVector &mv, int normType, string str);
  typedef double ST;
  typedef Teuchos::ScalarTraits<ST> SCT;
  typedef SCT::magnitudeType MT;
  typedef Epetra_MultiVector MV;
  typedef Epetra_Operator OP;
  typedef Belos::MultiVecTraits<ST, MV> MVT;
  typedef Belos::OperatorTraits<ST, MV, OP> OPT;
  Teuchos::RCP<Ifpack_Preconditioner> prec;
  Teuchos::RCP<Belos::EpetraPrecOp> belosPrec;
  Teuchos::RCP<Belos::LinearProblem<double, MV, OP>> problem;
  Teuchos::RCP<Belos::SolverManager<double, MV, OP>> v_solve_iter;
};
#endif
